### PR TITLE
Add org for non-English beta test

### PR DESCRIPTION
**Pull request by davidmreed**
This PR adds a beta org with the language set to Spanish.

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by davisagli** [comment]
Hmm, looks like there are various tests making assertions about labels that don't pass in the Spanish org.

**Comment by force2b** [comment]
Thanks @davidmreed! It's interesting that these are failing in Master - before we've even merged any of the new translations.

**Comment by davidmreed** [comment]
@force2b  This is something that was requested a while back (I didn't mean to time it relative to the new translations!)

Based on the results I'm seeing for both Apex and Robot, it doesn't currently provide much value - too many tests fail based on translated differences. I'll share a writeup summary.

**Comment by davisagli** [comment]
@davidmreed is work on this still planned, or can we close it and delete the branch?

**Comment by davidmreed** [comment]
@davisagli  I'm going to merge it. The team committed to making the test builds on this org shape work.

**Pull request merged**
