### PR TITLE
[wip] Github Actions experimental branch

### PR DESCRIPTION
**Pull request by jstvz**
# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by force2b** [comment]
@jstvz  I don't think the action ran because there were no classes committed. Feel free to merge this into my branch and work there; or I can modify a class file in this branch. Either is good for me.

**Comment by jstvz** [comment]
@force2b I've tried a couple of approaches here, none of which appear to work correctly. The crux of the problem is that, by default, we've got a... strange git context, where not every ref is present. The last few commits here attempted to work around that by being more explicit about which refs to compare, but unfortunately the diffs don't match expectations. 

There may be a better approach here that makes use of the built-in diff url ([example](https://patch-diff.githubusercontent.com/raw/SalesforceFoundation/NPSP/pull/6529.diff)) to check for the strings we care about. Alternatively, a full-fledged local action offers more control, but at the risk of being overkill for this use case.

Thanks for the nerd snipe, btw.

**Comment by force2b** [comment]
Thanks @jstvz. So, the issue is the `git fetch` statement vs. the actual diff?

**Comment by jstvz** [comment]
> Thanks @jstvz. So, the issue is the `git fetch` statement vs. the actual diff?

Yeah, I think that's the case. For example, on a fresh clone:
```console
$ git branch --all | rg 234
  remotes/origin/feature/234
  remotes/origin/feature/234__gift-entry-soft-credits
  remotes/origin/feature/234__perftest-insert-contacts
  remotes/origin/feature/234__rdChangeHistoryMetadata
  remotes/origin/feature/234__undeliverableAddressToAccountAndContacts
$ git diff-tree master..feature/234 --patch-with-raw
fatal: ambiguous argument 'master..feature/234': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

The solution, I think, is that we need to pass a `refspec` to `git fetch` to resolve the reference:
```console
$ git fetch origin feature/234:feature/234
From github.com:SalesforceFoundation/NPSP
 * [new branch]          feature/234 -> feature/234
$ git diff-tree master..feature/234 --patch-with-raw
[...no diff...]
```

I can't get the workflow to fire to confirm, but that's my best guess.

**Comment by force2b** [comment]
@jstvz I think that worked! https://github.com/SalesforceFoundation/NPSP/pull/6292/checks?check_run_id=3032462005

**Pull request closed without merging**
