### PR TITLE
RD2: Schedule Visualization Field Security

### PR DESCRIPTION
**Pull request by andrewyu-salesforce**
As a user I want to see a standard experience when I do not have access to the fields displayed on a component so that I know how to resolve the issue.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by andrewyu-salesforce** [comment]
**lurch: attach W-039304

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hs23QAC" target="_blank">W-039304</a>

**Comment by andrewyu-salesforce** [comment]
Hello @RadSFDeveloper, The code is ready for review.

**Comment by andrewyu-salesforce** [comment]
**lurch: detach W-039304

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x1E000001Hs23QAC" target="_blank">W-039304</a>

**Pull request closed without merging**
