### PR TITLE
Hide unfriendly mappings in template builder sidebar

### PR DESCRIPTION
**Pull request by bdvorachek**
- Split field mappings into three sections in the template builder. Bundles, Basic and Advanced
- Added help text to several of the object mappings in the template builder
- Added expand all / collapse all links that are specific to each of the three sections
- Labels
  - geBodyFieldBundlesLeftCol
  - geHelpTextAccount1Mapping
  - geHelpTextAccount2Mapping
  - geHelpTextAddressMapping
  - geHelpTextAllocation1Mapping
  - geHelpTextAllocation2Mapping
  - geHelpTextAllocationBundle
  - geHelpTextContact1Mapping
  - geHelpTextContact2Mapping

# Critical Changes

# Changes
## Gift Entry Enhancements
- We refined the list of Template Builder fields to show the most common ones higher up in the screen and added information about how to use the different form fields and field bundles.

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by bdvorachek** [comment]
**lurch: attach W-038289

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hq4MQAS" target="_blank">W-038289</a>

**Comment by melissabarber** [comment]
Just reviewed all the changes with @bdvorachek. I'm all good to go with this PR when he pushes his changes discussed during our call. CC @ptewson-sfdo

**Comment by gjang-sfdo** [comment]
Looks good to me too for UX look and feel consistencies. Thanks! cc @ptewson-sfdo

**Pull request merged**
