### PR TITLE
Create a new test to check for default GAU on $0 opportunity

### PR DESCRIPTION
**Pull request by Julian88Tex**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by Julian88Tex** [comment]
lurch** W-035595

**Comment by Julian88Tex** [comment]
@skristem FYI not ready for review yet

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C9x9QAC" target="_blank">W-035595</a>

**Comment by Julian88Tex** [comment]
Going to close for now since it's been a while since I've had a chance to work on this and now have some competing priorities with a team switch that I'll need to focus on. Moved ticket back into "Dev Ready".

**Pull request closed without merging**
