### PR TITLE
Adoption: Video Header Banner

### PR DESCRIPTION
**Pull request by fparodi-salesforce**
# Critical Changes

# Changes
Create Video Header Banner component

# Issues Closed

# Community Ideas Delivered

# New Metadata

- Lightning Component Bundle
  - gsResources
<br/>

- Static Resource
  - CumulusStaticResources/gsAssets/Getting_started_header.svg

# Deleted Metadata

### CODE REVIEW

**Comment by fparodi-salesforce** [comment]
[W-7964410](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008IBNuIAO/view)
[W-8140210](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000089oBRIAY/view)

**Review by force2b — APPROVED** [review]

**Review by dcaballeroSf — APPROVED** [review]

**Comment by force2b** [comment]
@dcaballeroSf and @fparodi-salesforce  FYI. The branch name for this PR (`feature/adoption_Header-banner-commponent`) is not a "child" PR branch name. Because it's missing the double-underscore after "adoption" it's effectively equivalent to a direct child of `master` instead of `feature/adoption`. If this is not going to be the very first PR you merge (out of all the other PR's merging into `feature/adoption`), then I recommend renaming this branch to `feature/adoption__Header-banner-commponent` (basically adding in the missing underscore). Without that, this branch will not be sync'd to whatever else is merged into the parent branch. Keep in mind that when a branch is renamed it will close this PR and a new one will need to be opened.

**Comment by force2b** [comment]
@dcaballeroSf and @fparodi-salesforce I suspect that the branch naming issue is the root cause of the additional changed files in this PR - there are 72 changed files listed. You may need to recreate this branch from scratch being sure not to revert any of the changes to other unrelated files that are showing as changed in this PR.

**Comment by fparodi-salesforce** [comment]
Close and re-opened with a new branch name https://github.com/SalesforceFoundation/NPSP/pull/5948

**Pull request closed without merging**
