### PR TITLE
Dispatch Scheduled Jobs from Apex

### PR DESCRIPTION
**Pull request by koenwesselman**
# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered
* Dispatch Scheduled Jobs from Apex

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by coriobriensfdo** [comment]
Hi @koenwesselman I'm really sorry but it appears that I missed asking you to sign our Contributor Licence Agreement back in June. Can you please email me at cori.obrien@salesforce.org and we'll get that sorted? We'll need that signed before the team can review your PR and add it to their backlog for the NPSP.

**Comment by coriobriensfdo** [comment]
W-8712689

**Comment by npsp-reedestockton** [comment]
@koenwesselman Thank you very much for this contribution!!

We have created an internal PR with your code and are currently working on it.  We made some minor changes to reflect internal style guidelines and to leave open the possibility for future extensions to your work.  The core of your contribution remains unaltered, and we thank you very much for your great work!!!

It is likely we will add this work to NPSP during our current sprint.

All the best!!

**Comment by koenwesselman** [comment]
Great, thanks Reede! :-)

**Pull request closed without merging**
