### PR TITLE
W-8033819 - GAU Allocations RD and Oppt in BDI

### PR DESCRIPTION
**Pull request by callen-sfdo**
Adds the ability for GAU Allocation records to be created at the Recurring donation level and flow down to closed won opportunities that were created by BDI in the same transaction context.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by coriobriensfdo** [comment]
> Thanks for the contribution! It looks like @fparodi-salesforce @e-ferrando is an internal user so signing the CLA is not required. However, [we need to confirm this](https://docs.google.com/forms/d/e/1FAIpQLSfB_vIrwFLweXIGt7ID98JhISCU2zm2ErOugAnGAcCvAzr7NQ/viewform).

@fparodi-salesforce and @e-ferrando can you both please click the link to complete the Google doc form to confirm you're part of the Salesforce.org org?

**Comment by force2b** [comment]
@callen-sfdo I noticed that the branch on this PR might be incorrect. It's merging from `feature/W-8033819-GAUAllocationSupportForRDInBDI` into `feature/RDInBDI`. However, both are these branches considered a child of `master`. That could create issues with the diff and might explain why there are 189 changed files in this PR. If this is actually a child branch of `feature/RDInBDI`, then the branch name for this should be something like `feature/RDInBDI__W-8033819-GAUAllocationSupport`.

**Comment by coriobriensfdo** [comment]
> > Thanks for the contribution! It looks like @fparodi-salesforce @e-ferrando is an internal user so signing the CLA is not required. However, [we need to confirm this](https://docs.google.com/forms/d/e/1FAIpQLSfB_vIrwFLweXIGt7ID98JhISCU2zm2ErOugAnGAcCvAzr7NQ/viewform).
> 
> @fparodi-salesforce and @e-ferrando can you both please click the link to complete the Google doc form to confirm you're part of the Salesforce.org org?

Please ignore this as I understand you are no longer working on this project with Salesforce.org.

**Comment by coriobriensfdo** [comment]
> Thanks for the contribution! It looks like @e-ferrando @fparodi-salesforce is an internal user so signing the CLA is not required. However, [we need to confirm this](https://docs.google.com/forms/d/e/1FAIpQLSfB_vIrwFLweXIGt7ID98JhISCU2zm2ErOugAnGAcCvAzr7NQ/viewform).

Ignore. The user is no longer working with Salesforce and therefore no longer has perms to this org. Manually removed the cla:missing label as this is not considered an external contribution.

**Pull request closed without merging**
