### PR TITLE
W-10049109 - [PAYMENT ALLOCATIONS] Payment Allocations Rounding Issue when Creating New Payments

### PR DESCRIPTION
**Pull request by jbrandolinisf**
- Note: This fix affects Payment Allocations only
- Removed logic from Allocations trigger to round percentage when calculating percentage for Payment Allocations when they are defaulted from the Opportunity
- Updated Test in ALLO_Allocations_TEST to account for change
- Added Test to ALLO_RecalculateService_TEST to confirm behavior there as well, with irrational percentage
- Updated assert methods in ALLO_UnitTestHelper_TEST to use double for percentage to maintain consistency

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by jbrandolinisf** [comment]
Original PR: https://github.com/SalesforceFoundation/NPSP/pull/6730

**Review by lparrott — APPROVED** [review]

**Review by force2b — APPROVED** [review]

**Comment by czheng-sf** [comment]
@jbrandolinisf - I added a release note, could you please have a look? Thanks in advance.

**Comment by jbrandolinisf** [comment]
> @jbrandolinisf - I added a release note, could you please have a look? Thanks in advance.

Hi @czheng-sf , 

Could we say something like this instead:

We fixed an issue that prevented Accounting Subledger's Payment Allocations functionality from accurately calculating the percentages for non-Default Allocations when first creating the Allocations from the Opportunity.  Note: Any allocations already created incorrectly will need to be corrected manually.

**Comment by czheng-sf** [comment]
Thanks @jbrandolinisf. I made some edits, could you please have a look?

**Comment by jbrandolinisf** [comment]
@czheng-sf - Looks good!!!

**Pull request merged**
