### PR TITLE
Ensure Reports Are Still Enabled for Recurring Donations

### PR DESCRIPTION
**Pull request by force2b**
- When installing the unmanaged metadata for RD2, ensure that Reports and Activity Tracking are still enabled as they are in the RD managed package.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by force2b** [comment]
**lurch attach: W-039236

**Comment by RadSFDeveloper** [comment]
**lurch: attach W-039236

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HrrPQAS" target="_blank">W-039236</a>

**Comment by rjanjanam** [comment]
Tested and Test charter as below
https://salesforce.quip.com/UeMMAIVptitS

**Pull request merged**
