### PR TITLE
Descriptions / Help Text Updates for gift entry fields

### PR DESCRIPTION
**Pull request by bdvorachek**
# Critical Changes

# Changes
- Updated the descriptions and inline help texts for various gift entry fields
# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by bdvorachek** [comment]
**lurch: attach W-039089

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HrXYQA0" target="_blank">W-039089</a>

**Comment by melissabarber** [comment]
@bdvorachek @ptewson-sfdo @vmartinov-sforg Reviewed during call with Ben and just did a quick run through in the PR. all good to go on my end!

**Comment by ptewson-sfdo** [comment]
@melissabarber just want to make sure you've seen this!

**Comment by melissabarber** [comment]
I'm all good with this one. Thanks @ptewson-sfdo!

**Pull request merged**
