### PR TITLE
RD2: Update metadeploy url

### PR DESCRIPTION
**Pull request by force2b**
# Critical Changes

# Changes

- When enabling Enhanced Recurring Donations, use the updated and final URL for Metadeploy to deploy the required special configuration for Enhanced Recurring Donations.

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by force2b** [comment]
**lurch: attach W-039415

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HsDMQA0" target="_blank">W-039415</a>

**Comment by RadSFDeveloper** [comment]
Related PR #5152

**Comment by Julian88Tex** [comment]
Noticed a several robot failures but checked with automation team and this is caused by other issues. I think there is a low risk of this ticket causing issues so will go ahead and merge.

**Pull request merged**
