### PR TITLE
Feature/adoption  title

### PR DESCRIPTION
**Pull request by dcaballeroSf**
# Critical Changes

# Changes
Adding the possibility to change the title in the Checklist
# Issues Closed

# Community Ideas Delivered

# New Metadata
Custom label:
    * gseuPageTitle
# Deleted Metadata

### CODE REVIEW

**Comment by dcaballeroSf** [comment]
[W-8716901](https://gus.lightning.force.com/a07B0000008mRhEIAU)

**Comment by force2b** [comment]
@dcaballeroSf Child branches should not merge into other child branches. This creates issues with automatic sync's from master. In this case, on the next merge into master, the master will sync directly into both of these branches instead of `feature/adoption__title` being sync'd from `feature/adoption__W-8545411-Checklist-Section-4`.

**Comment by force2b** [comment]
@dcaballeroSf That issue likely explains the merge conflict.

**Comment by dcaballeroSf** [comment]
The feature/adoption branch got deleted automatically and that changed all the destiny branches from pr. I restored the feature/adoption branch and redirected all the pr to it

**Review by force2b — APPROVED** [review]

**Pull request merged**
