### PR TITLE
W-9549849 Fix for incorrect scale on Recurring Donation Amount field on NPSP Data Import object

### PR DESCRIPTION
**Pull request by sgovindankutty**
Recurring Donation Amount field on NPSP Data Import object had incorrect Scale so updating the

scale value to avoid rounding off to the nearest whole number.
The change is performed on the DataImport__c object.

# Critical Changes

# Changes

# Issues Closed
Fixes: #[6523](https://github.com/SalesforceFoundation/NPSP/issues/6523)

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Review by callen-sfdo — APPROVED** [review]
looks good

**Comment by jesslopez-sf** [comment]
Hi @sgovindankutty  - would you mind linking the Github Issue to this PR please? You can say something like:
Fixes: #6523
in the Issues Closed section. Our Issue will then get closed automatically when this is released. Thank you!

**Comment by sgovindankutty** [comment]
> Hi @sgovindankutty - would you mind linking the Github Issue to this PR please? You can say something like:
> Fixes: #6523
> in the Issues Closed section. Our Issue will then get closed automatically when this is released. Thank you!

**Comment by sgovindankutty** [comment]
@jesslopez-sf  Updated the issue id!

**Pull request merged**
