### PR TITLE
Ensure Payments to be created table has an accessible label

### PR DESCRIPTION
**Pull request by bdvorachek**
WI - https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008EI0hIAG/view

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by bdvorachek** [comment]
@ptewson-sfdo - for you to review.

**Review by psadie-sfdo — APPROVED** [review]
Looks good to me! VoiceOver announced the correct title as I entered and left the table.

**Review by sokosaurus — APPROVED** [review]
Looks good to me!

**Review by ptewson-sfdo — APPROVED** [review]
Looks good!

**Comment by bdvorachek** [comment]
Closing this PR to base it off of the main branch rather than feature/232.

**Pull request closed without merging**
