### PR TITLE
Api v48 update

### PR DESCRIPTION
**Pull request by force2b**
- Update the API version on all packaged and unpackaged metadata to API v48.0 (Winter '20), with the exception of the Manage Household lightning components.

# Critical Changes

# Changes
- Update the API version on all Apex, Visualforce and Lightning metadata to API v48.0 (Winter '20).

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

# Unaggregated Pull Requests
* Api 48 update: Reset BDI & BGE Class versions [[PR5522](https://github.com/SalesforceFoundation/NPSP/pull/5522)]
* Api48: Reset GE and FORM class versions [[PR5524](https://github.com/SalesforceFoundation/NPSP/pull/5524)]

### CODE REVIEW

**Comment by skristem** [comment]
@RadSFDeveloper and @force2b the BGE test failures seem to be valid issues. Batch Dry Run seems to be failing, please check the screenshots on the failed tests.

**Comment by force2b** [comment]
Thanks @skristem. I'll look into it.

**Comment by force2b** [comment]
@codexmarcel Would you mind reviewing this PR for the `cumulusci.yml` and unpackaged metadata changes?

**Comment by force2b** [comment]
**lurch: attach W-035932

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAZ8QAO" target="_blank">W-035932</a>

**Pull request merged**
