### PR TITLE
Gift Entry: ui updates

### PR DESCRIPTION
**Pull request by psadie-sfdo**
# Critical Changes

# Changes
- Various UI updates to Gift Entry components
# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by psadie-sfdo** [comment]
**lurch: attach W-038954

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HrE2QAK" target="_blank">W-038954</a>

**Comment by ptewson-sfdo** [comment]
Prince - this is super nice and thank you! There's maybe a collision with the display of validation errors story that Gus just delivered in #5026. There's a couple of other differences with the orgs (one is namespaced, one is Winter '20, one is Spring '20), but maybe just look into how these errors are display: 

Non-NS org with this branch deployed:
image

Namespaced org with main feature branch:
image

**Comment by melissabarber** [comment]
@psadie-sfdo & @ptewson-sfdo I did a quick review of the Custom Label on this one.

**Comment by psadie-sfdo** [comment]
> Prince - this is super nice and thank you! There's maybe a collision with the display of validation errors story that Gus just delivered in #5026. There's a couple of other differences with the orgs (one is namespaced, one is Winter '20, one is Spring '20), but maybe just look into how these errors are display:
> 
> Non-NS org with this branch deployed:
> image
> 
> Namespaced org with main feature branch:
> image

Taking a look!

**Comment by psadie-sfdo** [comment]
**lurch: attach W-038984

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HrIYQA0" target="_blank">W-038984</a>

**Pull request merged**
