### PR TITLE
Fix broken links on Getting Started page

### PR DESCRIPTION
**Pull request by npsp-reedestockton**
We fixed the broken link for "View more on our youtube channel".

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by npsp-reedestockton** [comment]
@force2b This is ready for your review.  Thanks!
@sam-knox Would you please take a look at the PR description.  Thanks!

**Comment by npsp-reedestockton** [comment]
** lurch attach: W-038385

**Comment by RadSFDeveloper** [comment]
**lurch attach: W-038385

**Comment by rponti-sforg** [comment]
@codexmarcel @force2b The Feature - Prerelease continues to fail with this error:  https://sfdo-metaci.herokuapp.com/builds/225708

I have tried to rebuild without success.

**Comment by rponti-sforg** [comment]
> @codexmarcel @force2b The Feature - Prerelease continues to fail with this error: https://sfdo-metaci.herokuapp.com/builds/225708
> 
> I have tried to rebuild without success.

@codexmarcel @force2b Good morning.  This PR seems to keep having trouble with it's builds.  The Feature - Prerelease continues to fail with the same error.  The Feature Test looks to have stalled.  When you have a moment, can you take a peak?  Just let me know if you have any questions.  Thank you.

**Comment by force2b** [comment]
@rponti-sforg Release Engineering is working with core to get that resolved. For this sprint at least, I would ignore pre-release build failures.

**Comment by rponti-sforg** [comment]
> @rponti-sforg Release Engineering is working with core to get that resolved. For this sprint at least, I would ignore pre-release build failures.

@force2b Thank you Mike.  What about the Feature Test build?  Is that what RelEng is working on to resolve with Core or is the Prerelease build?  The Feature Test just seems to be stuck.

**Comment by force2b** [comment]
Sorry. Missed that. Just restarted it.

**Comment by rponti-sforg** [comment]
QE testing for this PR and associated WI is complete.  Based on the WI Description, ACs, PR comments, and test charter, tests have passed.

For further testing details, see: 
https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x1E000001HqFZQA0/view
https://salesforce.quip.com/RajDAyyMCzap

Merging PR.  Will set WI status to 'Closed' once PR post merge builds have passed.

**Pull request merged**
