### PR TITLE
[RD] Enable GA for Create Commitment from NPSP

### PR DESCRIPTION
**Pull request by andrewyu-salesforce**
Enable create commitment GA by removing Pilot Enabled verification.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by andrewyu-salesforce** [comment]
Attach To [WI-8486487](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008jtwqIAA/view)

**Comment by andrewyu-salesforce** [comment]
@RadSFDeveloper @npsp-reedestockton The code is ready for review

**Review by npsp-reedestockton — APPROVED** [review]
Looks good @andrewyu-salesforce

**Review by RadSFDeveloper — APPROVED** [review]
Looks good, thanks @andrewyu-salesforce !

**Comment by RadSFDeveloper** [comment]
@sam-knox , @mattwashington : Can you please review and update the PR description?

**Comment by sam-knox** [comment]
@RadSFDeveloper @mattwashington - I don't think this one needs a customer-facing release note. We will of course announce the new functionality related to this during the Spring release.

**Pull request merged**
