### PR TITLE
Feature/adoption  trailhead component

### PR DESCRIPTION
**Pull request by dcaballeroSf**
# Critical Changes

# Changes
    Creating a new component for linking to Trailhead to be used in the End User Page
# Issues Closed

# Community Ideas Delivered

# New Metadata
    LWC
        * euTrailhead
    Custom Labels
        * euExploreTrailheadButton
        * euTrailheadText
# Deleted Metadata

### CODE REVIEW

**Comment by dcaballeroSf** [comment]
[W-8549969](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008l2fLIAQ/view)

**Comment by force2b** [comment]
@dcaballeroSf Is this for the "End User Get Started" page or something else?

**Comment by force2b** [comment]
@davidmreed Do you know why the PR shows this error: "One or more contributors need to sign the CLA
Details"

**Comment by davidmreed** [comment]
Looks like @dcaballeroSf might have accidentally had some commits attributed to @diego-caballero, which account is not a member of `SalesforceFoundation`.

**Comment by coriobriensfdo** [comment]
> Looks like @dcaballeroSf might have accidentally had some commits attributed to @diego-caballero, which account is not a member of `SalesforceFoundation`.

Yes that's exactly why! We enabled a CLA bot to automatically request signature for all external contributions a few weeks ago.

**Comment by dcaballeroSf** [comment]
@davidmreed Any idea of how could it happened? That's account (diego-caballero) it's an old github account I havent used in ages(I think last time I used it was on 2014), during my PTO I have received github related emails in my personal account(I ignored them all). I haven't used this laptop for anything else.

**Comment by dcaballeroSf** [comment]
closing and fixing pr

**Pull request closed without merging**
