### PR TITLE
Add translations for MetaDeploy

### PR DESCRIPTION
**Pull request by davisagli**
This adds a top-level `metadeploy` folder with the translations for NPSP's MetaDeploy installation plans, from the Localization team. These will be updated in MetaDeploy when the installer for the next release is published.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by force2b** [comment]
@davisagli Pretty cool. Does MetaDeploy use the language of the machine/browser to determine which language to display?

**Comment by davisagli** [comment]
@force2b yeah, it tries to use the preferred language based on the Accept-Language HTTP request header sent by the browser.

**Comment by force2b** [comment]
Is it testable now, or does it need to merge and then wait for the next MetaDeploy release to be available?

**Comment by davisagli** [comment]
@force2b the translations will be added to MetaDeploy's database the next time the installers are published after this is merged.

**Comment by force2b** [comment]
Thanks @davisagli. Approved.

**Pull request merged**
