### PR TITLE
W-10049109 - [PAYMENT ALLOCATIONS] Payment Allocations Rounding Issue when Creating New Payments

### PR DESCRIPTION
**Pull request by jbrandolinisf**
- Note: This fix affects Payment Allocations only
- Removed logic from Allocations trigger to round percentage when calculating percentage for Payment Allocations when they are defaulted from the Opportunity
- Updated Test in ALLO_Allocations_TEST to account for change
- Added Test to ALLO_RecalculateService_TEST to confirm behavior there as well, with irrational percentage
- Updated assert methods in ALLO_UnitTestHelper_TEST to use double for percentage to maintain consistency

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by weizsforg** [comment]
Looks good to me! Can you ping the NPSP team to review it also? @jbrandolinisf Also, somehow some of the Feature Test flows are not running in this PR.

**Review by weizsforg — APPROVED** [review]

**Review by lparrott — APPROVED** [review]
Looks good! We'll need to update the target branch once this is approved for release, since 235 contains changes not meant for a patch release at this point.

**Comment by jbrandolinisf** [comment]
@lparrott - Let me know when-- I assume the target will be main/master?

**Comment by jbrandolinisf** [comment]
@lparrott - What branch should I be targeting?

**Comment by lparrott** [comment]
@jbrandolinisf We can switch it to `main` once this change gets approved for a patch release.

**Pull request closed without merging**
