### PR TITLE
Revert GAU CRLP bug fix due to regression

### PR DESCRIPTION
**Pull request by npsp-reedestockton**
We discovered a regression in the fix to a General Accounting Unit Customizable Rollups issue, so we are rolling back the fix until the regression is addressed.
# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by npsp-reedestockton** [comment]
@lparrott @andrewyu-salesforce This PR reverts the previous change.  Would appreciate your review. 

@sam-knox Please check the description.  This reverts an issue fix due to a regression.

**Review by lparrott — APPROVED** [review]
@npsp-reedestockton Thanks for double checking this change, and preventing a regression! We'll tackle the bug with a better approach next round.

**Comment by sam-knox** [comment]
@npsp-reedestockton - Can do. Will you post a link to the WI so I can see that too? Thanks!

**Comment by npsp-reedestockton** [comment]
> @npsp-reedestockton - Can do. Will you post a link to the WI so I can see that too? Thanks!

Yes, I will.  I'm holding off until we discuss.  We may want a new WI.  As soon as that is clarified, I will post the link.

**Review by andrewyu-salesforce — APPROVED** [review]

**Comment by npsp-reedestockton** [comment]
> > @npsp-reedestockton - Can do. Will you post a link to the WI so I can see that too? Thanks!
> 
> Yes, I will. I'm holding off until we discuss. We may want a new WI. As soon as that is clarified, I will post the link.

For now, linking to the original - [W-8818353](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000095CUJIA2/view)

**Pull request merged**
