### PR TITLE
[Robot][GE] Robot test for field reorder verification

### PR DESCRIPTION
**Pull request by schlossmj**
# Critical Changes

# Changes

# Issues Closed
https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x1E000001HsTcQAK/view

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Review by rjanjanam — APPROVED** [review]
Looks Good

**Comment by force2b** [comment]
@schlossmj Just looking at this old PR with merge conflicts and wondering if the PR and branch are still needed. If not, would you mind deleting? Thanks.

**Comment by schlossmj** [comment]
> @schlossmj Just looking at this old PR with merge conflicts and wondering if the PR and branch are still needed. If not, would you mind deleting? Thanks.

@force2b We will be completing this in the next 2-3 sprints.

**Comment by force2b** [comment]
Thanks @schlossmj. Though, I'm curious why it merges into master, but is using the parent-child branch name strategy. Was there a parent `feature/robot` branch at one time that has been deleted?

**Pull request closed without merging**
