### PR TITLE
Show elevate widget based on configured payment methods.

### PR DESCRIPTION
**Pull request by npsp-reedestockton**
When entering gifts via batch, we now display the Elevate widget based on configured payment types.
# Critical Changes

# Changes
- We've updated the Gift Entry Elevate widget to reflect the payment types that are set up in Elevate.

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by npsp-reedestockton** [comment]
Tracking [W-11565029](https://gus.lightning.force.com/lightning/r/a07EE000013ZQyHYAW/view)

**Comment by npsp-reedestockton** [comment]
@voduyemi @andrewyu-salesforce Would appreciate your feedback on this PR.

**Review by voduyemi — APPROVED** [review]
Looks good to me @npsp-reedestockton, Are we going to be writing the jest tests for this change in a different PR?

**Review by andrewyu-salesforce — APPROVED** [review]

**Comment by andrewyu-salesforce** [comment]
@npsp-reedestockton there is a test failure

**Comment by npsp-reedestockton** [comment]
@voduyemi @andrewyu-salesforce Made a small change, but until we are 100% sure we can do ACH in batch, I do not recommend reviewing again. Also, will defer jest tests until then as well.

**Comment by lparrott** [comment]
Merged as part of #7112

**Pull request closed without merging**
