### PR TITLE
[Robot]GE lookups related fields validation

### PR DESCRIPTION
**Pull request by skristem**
Creates a template with different types of opportunity fields, with default values in Record Type and Description fields. Verifies defaults are loaded correctly on the batch gift form. Verifies picklist values are updated correctly for different record types. When an opportunity is selected from Review Donations > Update Opportunity, verifies related values are auto-populated correctly. When opportunity contains a value in the field that has default, verifies opportunity value is updated in the field upon opportunity selection. When opportunity does not contain a value in the field that has default, verifies field default is not cleared upon opportunity selection.

To run the test: **cci task run robot -o suites robot/Cumulus/tests/browser/gift_entry/opp_lookups_related_fields.robot --org <org name>**
if you wish to run test without opening a browser window then, to the above command pass" -o vars BROWSER:headless" at the end.

Created a keyword for batch creation to remove code repetition and hence updated impacted tests with that keyword.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Review by deepmalamehta — APPROVED** [review]

**Review by Safiyab — APPROVED** [review]
Looks great! Since you added a keyword, it would be good to run the libdoc task once.

**Review by vmartinov-sforg — COMMENTED** [review]
I am getting this error when running the test. 

==============================================================================
Opp Lookups Related Fields                                                    
==============================================================================
Verify Opportunity Related Field Values Autopopulate Correctly :: ... | FAIL |
Parent suite setup failed:
IndexError: Given index 0 is out of the range 0--1.
------------------------------------------------------------------------------
Opp Lookups Related Fields                                            | FAIL |
Suite setup failed:
IndexError: Given index 0 is out of the range 0--1.

**Review by rjanjanam — APPROVED** [review]
Looks Good!

**Comment by skristem** [comment]
@vmartinov-sforg you get that error because NPSP settings were not loaded. There is a bug I had reported a while back about this W-8119513. As a workaround patrick suggested opening the NPSP settings page first on the org and then run the tests. This and most of GE tests check if GE is enabled with an API call and that setting is not loaded until you open NPSP Settings page.

**Review by psadie-sfdo — APPROVED** [review]

**Review by vmartinov-sforg — APPROVED** [review]

**Review by schlossmj — APPROVED** [review]

**Pull request merged**
