### PR TITLE
RD2: Send Campaign Info to Elevate

### PR DESCRIPTION
**Pull request by andrewyu-salesforce**
# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by andrewyu-salesforce** [comment]
track [W-8334258](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008i8qPIAQ/view)

**Comment by andrewyu-salesforce** [comment]
@RadSFDeveloper @npsp-reedestockton The code is ready for you.

**Review by RadSFDeveloper — APPROVED** [review]
Looks great, thank you @andrewyu-salesforce !

**Review by npsp-reedestockton — APPROVED** [review]
Looks great, Andrew!!

**Pull request merged**
