### PR TITLE
Fix table header and row issues on Contact Merge

### PR DESCRIPTION
**Pull request by npsp-reedestockton**
- We corrected several accessibility issues on the Contact Merge page: improper association of table headers and rows, a missing heading, and an active link improperly located in a table header row.

# Critical Changes

# Changes
- We corrected several accessibility issues on the Contact Merge page.

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by npsp-reedestockton** [comment]
**lurch:attach W-042097

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000007hbarQAA" target="_blank">W-042097</a>

**Comment by npsp-reedestockton** [comment]
@force2b @andrewyu-salesforce This is ready for review. Thanks!

@sam-knox "Select" label heading has been added to the search results table on Contact Merge and "Select All" row heading has been added to the Select Contacts comparison table on Contact Merge.  Both are existing labels, but this usage is new.

**Comment by force2b** [comment]
@npsp-reedestockton Overall the functionality works, however the one issue I see is that the two new header rows use a larger font size. As a result they look a bit odd to me.
image

**Comment by npsp-reedestockton** [comment]
Thanks for pointing that out, Mike.  I've been looking at this page for so long it didn't even register that the font size was wrong.

**Comment by force2b** [comment]
Thanks @npsp-reedestockton. The "Select All" line is better, but the Contact name row is still large relative to the other text on the page.
image

**Comment by npsp-reedestockton** [comment]
@force2b Take a quick peek at the production version.  I think you'll find that the contact name line is the same size.  If you still want it to change, okay, but that's not a result of the current code modifications.

**Pull request merged**
