### PR TITLE
CCI: Test Data Snowfakery Recipe and Flow Updates

### PR DESCRIPTION
**Pull request by force2b**
- Update the  test data flow to use new features available in the latest version of Snowfakery
- Rename the original `ldv_test_data` flow to `ldv_test_data_rd2`  because it creates RD2 records with the Opps
- Created a new flow `ldv_test_data` that generates Contacts and Opps _without_ RD2 records

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by force2b** [comment]
@prescod If this looks good, would you mind approving?

**Comment by force2b** [comment]
@prescod Hi Paul. If this PR looks good for changes to the snowfakery flows would you mind approving?

**Review by prescod — APPROVED** [review]

**Comment by force2b** [comment]
@prescod Thank you for the approval. Oddly though, it still says merging is blocked because of a missing review. I wonder if the `release-engineering-reviewers` group needs to approve too?

**Comment by prescod** [comment]
Yes it looks like our policy requires you to get buy-in from an "ERE".

**Review by davidmreed — APPROVED** [review]

**Pull request merged**
