### PR TITLE
[W-11356040/W-11312734] RD Responsive Fix.

### PR DESCRIPTION
**Pull request by maurimart**
Table responsive columns
 Columns resize logic

# Work Items
[W-11312734](https://gus.lightning.force.com/a07EE00000zS5OIYA0)
[W-11356040](https://gus.lightning.force.com/a07EE000010CQkIYAW)

# Changes

### CODE REVIEW

**Review by lparrott — APPROVED** [review]

**Review by JoseRossiSF — APPROVED** [review]
LGTM

**Review by gerardorodriguezsf — APPROVED** [review]

**Comment by force2b** [comment]
@maurimart Please fix the PR comment. The changes made are not considered "critical changes".  These bubble up to customers as a notice that they must take action on the changes. That's not at all what these are.

**Comment by JoseRossiSF** [comment]
> @maurimart Please fix the PR comment. The changes made are not considered "critical changes". These bubble up to customers as a notice that they must take action on the changes. That's not at all what these are.

@force2b thank you, Michael. @maurimart , I've updated the PR comments

**Comment by force2b** [comment]
Conflicts require resolution

**Pull request merged**
