### PR TITLE
Fix batch progress display during RD migration

### PR DESCRIPTION
**Pull request by npsp-reedestockton**
We fixed a bug that caused the progress display to fail during Enhanced Recurring Donation validation and migration.
# Critical Changes

# Changes

# Issues Closed
- [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V0000029kbWQAQ): Recurring Donations: Batch progress component does not display during Data Validation or Run Migration steps and the user instead sees errors
# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by npsp-reedestockton** [comment]
@lparrott @balsamhindi Would appreciate your feedback on this PR. Thanks!

**Comment by npsp-reedestockton** [comment]
Tracking [W-11105735](https://gus.lightning.force.com/lightning/r/a07EE00000wSQCHYA4/view)

**Review by lparrott — APPROVED** [review]
Great find, this fixed the scenario that I tested 👍

**Review by balsamhindi — APPROVED** [review]
Looks good to me Reede!

**Pull request merged**
