### PR TITLE
Gift Entry: Handle purchase errors

### PR DESCRIPTION
**Pull request by vmartinov-sforg**
# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by vmartinov-sforg** [comment]
**lurch: attach W-039750

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HsnDQAS" target="_blank">W-039750</a>

**Comment by vmartinov-sforg** [comment]
close the PR re: secret api key

**Comment by vmartinov-sforg** [comment]
closing

**Comment by vmartinov-sforg** [comment]
closing

**Pull request closed without merging**
