### PR TITLE
W-8066545 Elevate Donor Cover

### PR DESCRIPTION
**Pull request by mldyang**
# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata
- New field on Payment object (npe01__OppPayment__c) - Donor_Cover_Amount__c
- New field on NPSP Data Import object (DataImport__c) - Payment_Donor_Cover_Amount__c
- New Custom Metadata Type mapping for the above fields

# Deleted Metadata

### CODE REVIEW

**Comment by grivero** [comment]
@mldyang  - No layout updates are needed, right?

**Comment by mldyang** [comment]
> @mldyang - No layout updates are needed, right?

@grivero yup no layout update. Per Shane https://gus.lightning.force.com/lightning/r/0D5B000001DrrmiKAB/view, since we have not added other Elevate specific fields previously, we don't add donor cover either to be consistent.

**Review by grivero — APPROVED** [review]

**Review by grivero — APPROVED** [review]
all good here

**Comment by grivero** [comment]
QA Passed 👍

**Pull request merged**
