### PR TITLE
RD2: Map RD "Day of Month" value of "31" to "Last Day of Month"

### PR DESCRIPTION
**Pull request by RadSFDeveloper**
Day Of Month set to 31 on new or updated RDs is mapped to "Last Day of Month" (Last_Day) value in order to avoid validation errors and ensure that RDs are properly inserted into NPSP.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by RadSFDeveloper** [comment]
**lurch: attach W-040931

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hv9pQAC" target="_blank">W-040931</a>

**Comment by force2b** [comment]
@sam-knox Would you mind reviewing the PR comment I just added for this PR?

**Comment by sam-knox** [comment]
@force2b - Just to verify, any record inserted with "31" converts to "Last Day of Month"? Whether it's through the API or front-end?

**Comment by force2b** [comment]
That is correct @sam-knox

**Pull request merged**
