### PR TITLE
Update jQuery and jQueryUI

### PR DESCRIPTION
**Pull request by npsp-reedestockton**
We updated third party libraries jQuery and jQueryUI to versions with no known vulnerabilities.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by npsp-reedestockton** [comment]
**lurch: attach W-039939

**Comment by npsp-reedestockton** [comment]
@force2b Could you please review?  Thanks!
@sam-knox Could you please review the pull description?  Thanks!

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HtAFQA0" target="_blank">W-039939</a>

**Comment by rponti-sforg** [comment]
@npsp-reedestockton @force2b Reede / Mike it looks like Feature Test - Namespaced build has stalled.  Can you restart it when you have the chance?  I have the ability to 'Rebuild' on builds that failed but I don't know how or where I can restart them if they have stalled.  Maybe missing something obvious. Thank you.

**Comment by force2b** [comment]
@rponti-sforg I just restarted the rebuild on that one.

**Comment by rponti-sforg** [comment]
QE testing is complete for this PR and associated WI. Based on WI Description, ACs, and supplemental documentation, tests have passed.

For further testing details, see:
WI: https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x1E000001HtAFQA0/view
Test Charter: https://salesforce.quip.com/paczAnKgkXwH

Will move forward with merging PR depending upon outcome of **Namespaced** and **Robot** Feature Tests. Will set corresponding WI to '**Closed**' once post merge builds are posted as 'success'.

**Comment by rponti-sforg** [comment]
@force2b @npsp-reedestockton @sam-knox I am ready to merge this.  However, I noticed that there is a pending reviewer request for the pull description.  I think I can go ahead with merge but wanted to check first.

**Comment by rponti-sforg** [comment]
@force2b @npsp-reedestockton Do we need to be concerned with this error build:
W-039939_PR_Post Merge Builds_1

These did pass:
W-039939_PR_Post Merge Builds

Let me know what you think.

**Comment by force2b** [comment]
@rponti-sforg Thanks. The pre-release build is bonked across the board for now. The others all look solid, other than the Robot Beta build which has also not passed since Beta 19. I'd say this is good to go.

**Pull request merged**
