### PR TITLE
Accessibility: Update alternative text on Manage Households "Add" buttons

### PR DESCRIPTION
**Pull request by npsp-reedestockton**
We added alternative text to image buttons in the Manage Households page.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by npsp-reedestockton** [comment]
Tracking #[W-7832109](https://gus.lightning.force.com/a07B0000008T2sWIAS)

**Review by RadSFDeveloper — APPROVED** [review]
Thanks @npsp-reedestockton !

**Comment by npsp-reedestockton** [comment]
Original PR closed to rename branch.  Reference PR#5815 for original comments/conversation/approvals.

**Comment by npsp-reedestockton** [comment]
@CrystalPreston-Watson Need to delete original branch due to naming error, so the PR had to be re-created as well.

**Comment by RadSFDeveloper** [comment]
@rjanjanam , can you please check into [robot test failures](https://sfdo-metaci.herokuapp.com/builds/316608/tests) next week? Thanks.
CC @npsp-reedestockton , @ravensisco

**Comment by npsp-reedestockton** [comment]
@rjanjanam The two robot test failures on ManageHouseholds are data locator issues directly caused by the changes in this work item.  The "Add" button still begins with "Add", but the name of the record (Contact) begin added is appended to the Add.  Please let me know if you want me to add a locator for this.  Thanks!

**Comment by rjanjanam** [comment]
> @rjanjanam The two robot test failures on ManageHouseholds are data locator issues directly caused by the changes in this work item. The "Add" button still begins with "Add", but the name of the record (Contact) begin added is appended to the Add. Please let me know if you want me to add a locator for this. Thanks!

@npsp-reedestockton  yes they are failing due to locator change. Please add a data-qa-locator and comment out the failing tests with the line below. That way they will not run as part of the build and later I can fix it.
[tags]                                  unstable

**Comment by RadSFDeveloper** [comment]
@npsp-reedestockton , thanks for making the changes.
@ravensisco : builds passed. This PR can be merged as soon as the merge freeze is lifted, there is no other outstanding task.

**Review by ravensisco — APPROVED** [review]
Testing has passed by A11y QE

**Pull request merged**
