### PR TITLE
Fix to Giving Page Dashboard for Amount This Year component

### PR DESCRIPTION
**Pull request by force2b**
- Only impacts unmanaged metadata for net new installs. Existing Customers are unchanged.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Review by andrewyu-salesforce — APPROVED** [review]

**Comment by force2b** [comment]
[W-8276127](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008hQ9CIAU/view)

**Comment by sam-knox** [comment]
@andrewyu-salesforce - Was there a GitHub Issue for this? If so, please link to it in Issues Closed.

**Comment by mattwashington** [comment]
@force2b @rjanjanam _Critical_ changes section? Or just the regular Changes section? I'm leaning towards critical, but wanted to run it by you.

**Comment by force2b** [comment]
@mattwashington Customers have to manually apply this change to their org if that helps decide the best place.

**Comment by mattwashington** [comment]
Understood. Thanks @force2b.

**Comment by jamesbsfdc** [comment]
Hi @mattwashington  Would it be possible to also do a shout out to the partner Kelly Johnson (https://powerofus.force.com/s/profile/0051E00000GSQi4QAH) who first highlighted the issue? No worries if this is not easily do-able as I could just comment on the release announcement when it goes out

**Comment by mattwashington** [comment]
@jamesbsfdc I'll be happy to. Checking with team on best method to give kudos. Thanks!

**Pull request merged**
