### PR TITLE
Update NPSP Error Email Message

### PR DESCRIPTION
**Pull request by melissabarber**
# Critical Changes

# Changes
- We updated the introduction in the NPSP Error Handling email to reduce confusion about the errors that may be included in the message.

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by melissabarber** [comment]
**lurch: attach W-041006

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HvHoQAK" target="_blank">W-041006</a>

**Comment by melissabarber** [comment]
> The label looks good.
> 
> @melissabarber Also, I think you can still merge this (I updated the branch to sync up to master this morning), but generally all branches should start with `feature/`. For example, `feature/mbarber/update-error-email-message`. You can read more about branch naming [here](https://salesforce.quip.com/lKb8AewriQ5A).

Thank you for the guidance, @force2b. I'm really new to this whole PR publishing thing.

@ptewson-sfdo I'll pass this over to you for final approval and merging. Please let me know if there's anything else I can do to help.

**Comment by melissabarber** [comment]
I named the branch incorrectly. Will close this PR and create anew.

**Pull request closed without merging**
