### PR TITLE
Contact Merge: Ensure all elements are accessible via keyboard

### PR DESCRIPTION
**Pull request by npsp-reedestockton**
We made all Contact Merge information accessible and accurate for keyboard-only users.
# Critical Changes

# Changes
 - We made all Contact Merge information accessible and accurate for keyboard-only users.

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata
Custom Labels
- conMergeStageNotStarted
- conMergeStageCurrent

# Deleted Metadata

### CODE REVIEW

**Comment by npsp-reedestockton** [comment]
Tracking [W-9533829](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000PtWmYAK/view)

**Comment by npsp-reedestockton** [comment]
@lparrott @andrewyu-salesforce Would appreciate your review.
@sam-knox Two new labels here.

Thanks all!

**Review by sam-knox — APPROVED** [review]

**Comment by andrewyu-salesforce** [comment]
@npsp-reedestockton The PR should be pointing to feature/235 instead of main

**Comment by npsp-reedestockton** [comment]
> @npsp-reedestockton The PR should be pointing to feature/235 instead of main

Thanks @andrewyu-salesforce!!  Fixed.

**Review by lparrott — APPROVED** [review]
Great solution for this! Just to note: I was able to test the new assistive text using Voice Over in Safari by pressing up and down, since these elements are not "tab-able".

**Review by andrewyu-salesforce — APPROVED** [review]

**Pull request merged**
