### PR TITLE
W-9595957 & W-8880804 - Fee Ingestion & UTM codes on Data Import

### PR DESCRIPTION
**Pull request by callen-sfdo**
- Adds fields for UTM codes to the Data Import object (with no associated data import field mappings)
- Adds fields for power of us fee ingestion to data import object and payment object and associated data import field mappings
- Adds new field mappings to install script

# Critical Changes

# Changes
 - We added fields to the NPSP Data Import object to support Google Analytics UTM parameters. We also added Elevate and payment gateway transaction fee fields to the NPSP Data Import and Payment objects. To use the new fields, grant Read and Edit access to these fields:
   - **NPSP DATA IMPORTS**
   - Payment Elevate Transaction Fee
   - Payment Gateway Transaction Fee
   - Payment Total Transaction Fees
   - UTM Source
   - UTM Medium
   - UTM Campaign
   - UTM Content
   - UTM Keyword Terms
   - **PAYMENTS**
   - Elevate Transaction Fee
   - Gateway Transaction Fee
   - Total Transaction Fees

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata
 - Fields
   - DataImport__c.Payment_Elevate_Transaction_Fee__c
   - DataImport__c.Payment_Gateway_Transaction_Fee__c
   - DataImport__c.Payment_Total_Transaction_Fees__c
   - DataImport__c.UTM_Source__c
   - DataImport__c.UTM_Medium__c
   - DataImport__c.UTM_Campaign__c
   - DataImport__c.UTM_Content__c
   - DataImport__c.UTM_Keyword_Terms__c
   - OppPayment__c.Elevate_Transaction_Fee__c
   - OppPayment__c.Gateway_Transaction_Fee__c
   - OppPayment__c.Total_Transaction_Fees__c

- New Data Import Field Mappings (which map the new fee fields from Data Import to the Payment)
   - Payment Elevate Transaction Fee
   - Payment Gateway Transaction Fee
   - Payment Total Transaction Fees

# Deleted Metadata

### CODE REVIEW

**Comment by mldyang** [comment]
@callen-sfdo should we add these new items to package.xml file as well?

**Review by sam-knox — APPROVED** [review]
Labels look good!

**Comment by callen-sfdo** [comment]
> @callen-sfdo should we add these new items to package.xml file as well?

@mldyang  I confirmed with David Reed this morning that we do not need to update package.xml for NPSP now that is it DX format.

**Review by mldyang — APPROVED** [review]
looks good!

**Pull request merged**
