### PR TITLE
Performance Tests: Update BDI Dataset filenames to match what's in the robot files.

### PR DESCRIPTION
**Pull request by force2b**
# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Review by boakley — COMMENTED** [review]
When I scan the code, I see a reference to the file with the wrong case in a comment. That should be made consistent with the actual filename:

# cci task run generate_and_load_from_yaml -o num_records_tablename DataImport__c -o num_records 10000 -o generator_yaml datasets/bdi_benchmark/BDI-With-Matching.recipe.yml --org whatever

**Comment by force2b** [comment]
@boakley Change made.

**Review by boakley — APPROVED** [review]
There were some test failures, but they don't look like they are related to this change. This change looks fine to me.

**Review by boakley — APPROVED** [review]
There were some test failures, but they look unrelated to this change. This change looks fine to me.

**Review by lparrott — APPROVED** [review]

**Pull request merged**
