### PR TITLE
[RD] Non-integration User Unable To Change Schedule Or Payment Type On Elevate RD

### PR DESCRIPTION
**Pull request by npsp-reedestockton**
We corrected a bug in the handling of Elevate-connected Recurring Donations which prevented non-Integration users from changing Installment Period or Payment Type.
# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by npsp-reedestockton** [comment]
Tracking [W-9313845](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000MhhXYAS/view)

**Review by lparrott — APPROVED** [review]
Looks good, I tested (with a non-integration User) that changing just the Day of Month is still being prevented, and that updating to a non-Elevate Payment Method throws a validation error. The changes we want to allow now work as intended 👍

**Comment by npsp-reedestockton** [comment]
@bdvorachek Could you please take a look and provide feedback?  Thanks!

@sam-knox This bug was fixed before release.  Not sure if you need to check out the description of the PR.

**Review by bdvorachek — APPROVED** [review]

**Comment by rponti-sforg** [comment]
QE testing is complete for this PR and subsequent WI.  ACs associated with WI have passed testing.

For further details and testing information, see:
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000MhhXYAS/view
https://salesforce.quip.com/1roMAJTYLbIK

Proceeding with merge of PR.  Will set WI status to 'Pending Release' and 'Closed' pending build(s) completion.

**Pull request merged**
