### PR TITLE
[Bug Bounty] Stored XSS work items

### PR DESCRIPTION
**Pull request by npsp-reedestockton**
These changes correct several stored XSS vulnerabilities.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by npsp-reedestockton** [comment]
***lurch: attach W-039356*

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hs7SQAS" target="_blank">W-039356</a>

**Comment by npsp-reedestockton** [comment]
@force2b @RadSFDeveloper Ready for review.

**Comment by force2b** [comment]
@npsp-reedestockton Very nice work. I think there is one more file using a confirm() with a label - [STG_PanelRelAuto](https://github.com/SalesforceFoundation/NPSP/blob/master/src/pages/STG_PanelRelAuto.page#L84)

**Comment by npsp-reedestockton** [comment]
Thanks for catching that missing file (STG_PanelRelAuto).  Added to PR.

**Comment by npsp-reedestockton** [comment]
Thanks for catching that missing file (STG_PanelRelAuto).  Added to PR.

**Pull request merged**
