### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by codexmarcel**
Adding the "Community Ideas Delivered" header to the pull request template.

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by codexmarcel** [comment]
W-038508 since I don't think I can invoke Lurch yet.

**Comment by codexmarcel** [comment]
**lurch: attach W-038508

**Comment by codexmarcel** [comment]
**lurch: attach W-038508

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HqUUQA0" target="_blank">W-038508</a>

**Comment by melissabarber** [comment]
Sorry to drop the review ball on this one, guys. Need anything else from me or will the header just start showing up on new PRs? @codexmarcel @davidmreed

**Comment by davidmreed** [comment]
Correct, @melissabarber!

**Pull request merged**
