### PR TITLE
Fix Merge Accounts SELF_REFERENCE_FROM_TRIGGER Error

### LINKED ISSUE #5850: Merging Accounts Asynchronously Results in SELF_REFERENCE_FROM_TRIGGER Error
This issue has been reported a few times by customers/partners (i.e. [#4134](https://github.com/SalesforceFoundation/NPSP/issues/4134) and [#3016](https://github.com/SalesforceFoundation/NPSP/issues/3016). But I don't see any further discussions in the Hub. 

### Summary
If customers are using non-npsp tools to merge records (from an MDM or even just other merge tools), they receive the following error when merging Household Accounts:
```
There was a problem Merging Account records: npsp.TDTM_Account: execution of AfterDelete

caused by: System.DmlException: 
Update failed. 
First exception on row 0 with id 001xxxxxxxxxxxx; 
first error: SELF_REFERENCE_FROM_TRIGGER, Object 001xxxxxxxxxxxx is currently in a merge operation, therefore a trigger can not update it.: []
```

### Stack Trace
```
Class.npsp.UTIL_DMLService.updateRecords: line 168, column 1
Class.npsp.HH_HouseholdNaming.UpdateNames: line 128, column 1
Class.npsp.HH_HouseholdNaming.renameHHAccounts: line 452, column 1
Class.npsp.ACCT_AccountMerge_TDTM.handleAccountMergeFixups: line 110, column 1
Class.npsp.ACCT_AccountMerge_TDTM.run: line 66, column 1
Class.npsp.TDTM_TriggerHandler.runClass: line 193, column 1
Class.npsp.TDTM_TriggerHandler.run: line 113, column 1
Class.npsp.TDTM_Config_API.run: line 92, column 1
Trigger.npsp.TDTM_Account: line 33, column 1 | DELETE_FAILED |
```

### Root Cause
This is occurring when a merge operation is called on Accounts asynchronously (I was not able to replicate synchronously via Execute Anonymous). Customers may opt for this method of merging since they are unable to programmatically call the NPSP Contact Merge code. The issue occurs when we attempt to rename the Account of the deleted Account's MasterRecordId.

We did modify the ACCT_AccountMerge_TDTM class in NPSP version 3.166, but I ran a test on 3.165 and still replicated the error.

### Steps to Repeat
1. Create an Apex Class called "BatchContactMerger". Replace the default text with the following:
```
public class BatchContactMerger implements Database.Batchable<SObject> {
	/* Note that this class only merges 2 Contacts and 2 Accounts at a time.
	 * The customer's system sends a pair of Contacts to merge (no more).
	 *	
         * Setup: none required. This will create 2 Contacts to merge.
	 * To run this batch class, enter the following in an Anonymous Apex window:
	 * 
         * Id contactBatchId = Database.executeBatch(new BatchContactMerger());
	*/  
    public Database.QueryLocator start(Database.BatchableContext bc) {
        List<Contact> contactList = new List<Contact>();
        contactList.add(new Contact(FirstName = 'Test', LastName='Test1'));
        contactList.add(new Contact(FirstName = 'Test', LastName='Test2'));
        insert contactList;

        String query = 'SELECT Id, AccountId FROM Contact WHERE LastName LIKE \'test%\'';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, list<Contact> scope){
        Set<Id> accountSet = new Set<Id>();
        
        for(Contact con:scope){
            accountSet.add(con.AccountId);
        }
        List<Account> accountList = [SELECT Id FROM Account WHERE ID IN: accountSet];
        
        // Merge Contacts
        merge scope[0] scope[1];
        
        //Merge their Accounts
        merge accountList[0] accountList[1];
        
    }
    
    public void finish(Database.BatchableContext BC){}
    
}
```
2. Run the following code in an Execute Anonymous Apex window:
`Id contactBatchId = Database.executeBatch(new BatchContactMerger());`

3. Confirm that the SELF_REFERENCE_FROM_TRIGGER is surfaced. 

**To confirm that the merge works synchronously:**
1. Replace all text in the Execute Anonymous Apex window with the following:
```
List<Contact> conList = new List<Contact>();
conList.add(new Contact(FirstName ='Jess', LastName = 'Test1'));
conList.add(new Contact(FirstName ='Jess', LastName = 'Test2'));
insert conList;
 
Set<Id> accountSet = new Set<Id>();
 
List<Contact> conList2 = [SELECT Id,AccountId FROM Contact WHERE LastName LIKE 'test%'];
for(Contact con:conList2){
    accountSet.add(con.AccountId);
}
 
List<Account> accountList = [SELECT Id FROM Account WHERE Id IN :accountSet];
        
merge conList2[0] conList2[1];
merge accountList[0] accountList[1];
```

2. Confirm that there are no errors.

### PR DESCRIPTION
**Pull request by npsp-reedestockton**
We fixed an error when merging accounts asynchronously.

# Critical Changes

# Changes

# Issues Closed
Fixes #5850

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by npsp-reedestockton** [comment]
@force2b @andrewyu-salesforce Ready for review
@kenlewis-sfdo Including you to make it easier for you to track changes in Account trigger
@sam-knox @mattwashington No label changes, but would appreciate it if you would take a look at change description.

**Comment by npsp-reedestockton** [comment]
Tracking [W-8092617](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008dH1yIAE/view)

**Review by force2b — APPROVED** [review]

**Review by andrewyu-salesforce — APPROVED** [review]

**Comment by npsp-reedestockton** [comment]
@lparrott @force2b @andrewyu-salesforce Minor changes per our discussions.  Would appreciate a quick re-review to make sure you are comfortable with adjustments.

**Review by lparrott — APPROVED** [review]
Changes look great @npsp-reedestockton, I'm glad we came up with a (hopefully temporary) fix to this. 

My only concern is around Unit test coverage, but since async merge isn't something we provide out of the box (customers implement it themselves) I think we can safely rely on regression tests from this WI.

**Review by andrewyu-salesforce — COMMENTED** [review]
@npsp-reedestockton nice work. glad we come out with the solution.

**Pull request merged**
