### PR TITLE
RD2: Data Migration handles Day of Month values of 29 and 30

### PR DESCRIPTION
**Pull request by RadSFDeveloper**
During Enhanced Recurring Donations enablement, Recurring Donations with a Day of Month values of 29 or 30 should be properly converted to the RD2 format while still retaining 29 and 30 picklist values.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by RadSFDeveloper** [comment]
**lurch: attach W-040429

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Hu4LQAS" target="_blank">W-040429</a>

**Comment by RadSFDeveloper** [comment]
@rponti-sforg , the PR is ready for testing.

**Comment by rponti-sforg** [comment]
QE testing is complete for this PR. Based on WI Description and ACs, tests have passed.

For further testing details, see:
https://foundation.lightning.force.com/lightning/r/agf__ADM_Work__c/a2x1E000001Hu4LQAS/view
https://salesforce.quip.com/EjakAwQc2yRq

Merging PR. Will monitor post merge builds. Once post merge builds pass, associated WI will be set to 'Closed'.

**Comment by rponti-sforg** [comment]
After sharing the Robot test failure (https://sfdo-metaci.herokuapp.com/tests/result/110262254) with Rata JanJanam, it was determined that it was a 'timing issue' which effected the finding of a Contact.  The error can be ignored and the merging of the PR can proceed.

**Pull request merged**
