### PR TITLE
Accessibility: Update alternative text on Manage Households "Add" buttons 

### PR DESCRIPTION
**Pull request by npsp-reedestockton**
We added alternative text to image buttons in the Manage Households page.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by npsp-reedestockton** [comment]
Tracking #[W-7832109](https://gus.lightning.force.com/a07B0000008T2sWIAS)

**Comment by npsp-reedestockton** [comment]
@force2b @RadSFDeveloper @andrewyu-salesforce Ready for review.  Thanks!

**Review by RadSFDeveloper — APPROVED** [review]
Looks good, thanks @npsp-reedestockton !

**Review by andrewyu-salesforce — APPROVED** [review]
@npsp-reedestockton Looks good

**Pull request closed without merging**
