### PR TITLE
Gift Entry: Fix for  lookup template defaults

### PR DESCRIPTION
**Pull request by voduyemi**
# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by annejackson** [comment]
Do we need to lurch what WI this was related to @voduyemi ?

**Comment by voduyemi** [comment]
@annejackson Yes we do, lurching right now.

**Comment by voduyemi** [comment]
**lurch: attach W-039046

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HrPeQAK" target="_blank">W-039046</a>

**Pull request merged**
