### PR TITLE
[W-11110825] - Renamed picklist options and picklist label

### PR DESCRIPTION
**Pull request by gerardorodriguezsf**
# Changes
Renames picklist options and picklist label

### CODE REVIEW

**Comment by gerardorodriguezsf** [comment]
[W-11110825](https://gus.lightning.force.com/a07EE00000wXHS2YAO)

**Review by andrewyu-salesforce — COMMENTED** [review]
@gerardorodriguezsf Generally all User facing label will need to be translatable and approved by the Doc team. In this case, I am not sure if Custom Label can be referenced in LWC metadata to be displayed in Experience Builder. Either way, Can you also assign the doc person as the reviewer for this PR so the text can be reviewed and approved and explore the option to use Custom Label instead of hardcoded text if possible

**Comment by gerardorodriguezsf** [comment]
> 

@andrewyu-salesforce

Custom Label can not be referenced in LWC metadata to be displayed in Experience Builder.

This is just a text update asked by @melissabarber [here](https://salesforce.quip.com/kRYaAjEE8aHr?range_cols=9&range_rows=1#temp:s:temp:C:PQJ39e645cd36ea4f44919fc2850;temp:C:PQJ8988ea61b07e4146ba30b62d7) and right now she is on vacations.
At this time, this is just to see what the picklist will look like in Experience Builder, there is no logic or apex controller.

**Comment by andrewyu-salesforce** [comment]
@gerardorodriguezsf If the work is only used for demonstration, then I don't think work is necessary to commit to the Feature/240 branch. The feature/240 branch is used to prepare for the 240 release. Only completed work should go into that branch. With that in mind, I also think the other works in the RecurringDonation Table on design data should not go into Feature/240. The 2 PRs which will be used for 'demo' purposes should not be in the Feature/240 branch. With that in mind, is there a reason why Test Data needs to be committed to the Feature/240 major branch?

**Comment by gerardorodriguezsf** [comment]
> @gerardorodriguezsf If the work is only used for demonstration, then I don't think work is necessary to commit to the Feature/240 branch. The feature/240 branch is used to prepare for the 240 release. Only completed work should go into that branch. With that in mind, I also think the other works in the RecurringDonation Table on design data should not go into Feature/240. The 2 PRs which will be used for 'demo' purposes should not be in the Feature/240 branch. With that in mind, is there a reason why Test Data needs to be committed to the Feature/240 major branch?


> @gerardorodriguezsf If the work is only used for demonstration, then I don't think work is necessary to commit to the Feature/240 branch. The feature/240 branch is used to prepare for the 240 release. Only completed work should go into that branch. With that in mind, I also think the other works in the RecurringDonation Table on design data should not go into Feature/240. The 2 PRs which will be used for 'demo' purposes should not be in the Feature/240 branch. With that in mind, is there a reason why Test Data needs to be committed to the Feature/240 major branch?

@andrewyu-salesforce We worked this way for release 238 with Benjamin, Luke @lparrott and Prince @psadie-sfdo .
All our PRs pointing to feature/240 will be used for release 240 and it's not only for a Demo.
Any Demo data will be removed in a later sprint iteration in the ticket [W-11165806](https://gus.lightning.force.com/a07EE00000xJvNMYA0)

FYI @alvaroolivenciasf @dvenor

**Review by andrewyu-salesforce — APPROVED** [review]

**Pull request merged**
