### PR TITLE
[A11y] Ensure pages reflow without loss of content or functionality when zoomed

### PR DESCRIPTION
**Pull request by lparrott**
- We updated Visualforce Pages to not truncate text, and not require horizontal scrolling, when zoomed in.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by npsp-reedestockton** [comment]
Tracking [W-7965336](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008UEbTIAW/view)

**Comment by npsp-reedestockton** [comment]
@lparrott @andrewyu-salesforce Would appreciate your review when you have time.  Thanks!

**Review by andrewyu-salesforce — APPROVED** [review]
@npsp-reedestockton Great work

**Comment by rponti-sforg** [comment]
QE testing for this PR and subsequent WI is now complete.  Based on the WI Description, ACs, PR comments, Test Charter feedback, and regression testing, tests have passed.

For further WI and testing details, see:
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008UEbTIAW/view
https://salesforce.quip.com/Vx6HAtHRxbZa

PR has been successfully merged and corresponding WI status has been set to 'Closed'.

**Pull request merged**
