### PR TITLE
RD2: Refresh NPSP Settings > Recurring Donation pages on enablement

### LINKED ISSUE #4965: Error visible in NPSP Settings- npsp:RD2_EnablementDelegate$controller$handleDryRunError
**Issue:**
In an org with version 3.168, navigating to NPSP Settings displays an error on each page.

"This page has an error. You might just need to refresh it. Action failed: npsp:RD2_EnablementDelegate$controller$handleDryRunError [response is not defined] Failing descriptor: {npsp:RD2_EnablementDelegate$controller$handleDryRunError}"

Screen Shot 2020-01-15 at 11 31 01 AM

**Steps to Repro:**

1. In an org with 3.168 installed, navigate to NPSP Settings. 
2. Notice error along bottom of screen on any page. Happens with or without CRLP enabled, and without any hidden RD2 code enabled.

Further investigation details to be added to Work Item.

### PR DESCRIPTION
**Pull request by RadSFDeveloper**
# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by RadSFDeveloper** [comment]
**lurch: attach W-038698

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HqqkQAC" target="_blank">W-038698</a>

**Comment by RadSFDeveloper** [comment]
**lurch: attach W-038704

**Comment by RadSFDeveloper** [comment]
**lurch: detach W-038698

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x1E000001HqqkQAC" target="_blank">W-038698</a>

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HqrEQAS" target="_blank">W-038704</a>

**Comment by RadSFDeveloper** [comment]
@ravensisco , the PR is ready for testing.

**Pull request merged**
