### PR TITLE
Updates to perf tests

### PR DESCRIPTION
**Pull request by prescod**
Updates to fix perf builds.

### CODE REVIEW

**Comment by prescod** [comment]
I don't know if we can merge with the flaky test, but I'd like to at least get it reviewed.

**Comment by davidmreed** [comment]
@prescod I'm fine with approving this, but what's the flakiness you reference? Is that one of the three Robot tests that is not currently passing?

**Comment by prescod** [comment]
@davidmreed Yes the three tests that are failing.

**Comment by prescod** [comment]
@davidmreed Can you merge please? Performance tests for this repo are broken until these fixes come through.

**Review by davidmreed — APPROVED** [review]

**Pull request merged**
