### PR TITLE
RD2: Close Elevate Recurring Donation by non-Elevate user

### PR DESCRIPTION
**Pull request by RadSFDeveloper**
# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by RadSFDeveloper** [comment]
Attached to [W-8251879](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008hA1JIAU/view)

**Review by andrewyu-salesforce — APPROVED** [review]
@RadSFDeveloper Everything looks good. Thanks for such a quick update.

**Review by npsp-reedestockton — APPROVED** [review]
Nice!

**Comment by rponti-sforg** [comment]
QE testing is complete for this PR and subsequent WI.

For further testing details, see: 
https://salesforce.quip.com/hvStAQPEA3As#YGIACA2lWyX

Proceeding with PR merge.

**Pull request merged**
