### PR TITLE
RD2 : Fixed Length RD Visualization(For Reference Will Remove)

### PR DESCRIPTION
**Pull request by andrewyu-salesforce**
As a user I want to see the future installments for my fixed length donations so that I can understand expected installments.

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by andrewyu-salesforce** [comment]
**lurch: attach W-039803

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HsrrQAC" target="_blank">W-039803</a>

**Comment by andrewyu-salesforce** [comment]
**lurch: detach W-039803

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x1E000001HsrrQAC" target="_blank">W-039803</a>

**Pull request closed without merging**
