### PR TITLE
Gift Entry: add Object Mapping 'imported' fields as a simulated Field Mappings

### PR DESCRIPTION
**Pull request by psadie-sfdo**
# Critical Changes

# Changes
- Simulate Object Mapping 'imported' fields as Field Mappings

# Issues Closed

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by psadie-sfdo** [comment]
**lurch: W-037936

**Comment by psadie-sfdo** [comment]
**lurch: attach W-037222

**Comment by psadie-sfdo** [comment]
**lurch: attach W-037222

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001Ho7bQAC" target="_blank">W-037222</a>

**Pull request merged**
