### PR TITLE
W-14308598 set batch default Values for GAU Allocation fields

### PR DESCRIPTION
**Pull request by salesforce-suyash-more**
# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# Features Intended for Future Release

# Features for Elevate Customers

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Review by lparrott — APPROVED** [review]
This change looks good! Will this have any effect on existing Templates?

**Comment by salesforce-suyash-more** [comment]
@lparrott, this will not affect existing templates since we are only modifying how the batch-defaults JSON object is populated.

**Comment by lparrott** [comment]
@salesforce-suyash-more looks like there was a test failure, mind taking a look? Doesn't look related to your change though...

**Comment by salesforce-suyash-more** [comment]
@lparrott, I have rebuilt the 'Feature Test' check, and it has passed all tests.

**Review by lparrott — APPROVED** [review]

**Pull request merged**
