### PR TITLE
updated enabled bdi and bdi custom objects test cases as per new gift…

### PR DESCRIPTION
**Pull request by skristem**
… entry feature

# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by annejackson** [comment]
I added @ptewson-sfdo as a reviewer if he could take a look and dev review this as well. This is for adding automation support/changes for the new advanced mapping page with gift entry enablement. @skristem are you expecting the Feature Tests- Robot to pass?

**Comment by skristem** [comment]
@annejackson the failing tests are falky tests not related to bdi and they r fixed as part of spring20 PR so I am not worried about those failed tests

**Comment by annejackson** [comment]
> I just want to make sure we are enabling gift entry as well.

I don't know if we want that yet @deepmalamehta  as the primary concern is making sure everything works with gift entry off first. I think manual enablement to test it with it on would be good for now. what are your thoughts @skristem ?

**Comment by skristem** [comment]
look at the files changed tab and there is a file starts with 1_enable_bdi, it clearly specifies the steps being done. As per deepa WI request, it first enables AM and waits for it be enabled and then enables Gift Entry and waits for it to be enabled. I can execute this and show it to u both in tomorrow functional review call @deepmalamehta and @annejackson

**Comment by skristem** [comment]
@rjanjanam took out the commented code

**Pull request merged**
