### PR TITLE
NPSP/Adoption LQA fixes for Spring '21

### PR DESCRIPTION
**Pull request by dmkud**
# Critical Changes

Translation fixes for Spring '21

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Review by bdvorachek — APPROVED** [review]

**Review by force2b — APPROVED** [review]

**Comment by force2b** [comment]
@bdvorachek and @dmkud Any concerns if I merge this?

**Comment by bdvorachek** [comment]
> @bdvorachek and @dmkud Any concerns if I merge this?

All good on my end.

**Comment by dmkud** [comment]
> @bdvorachek and @dmkud Any concerns if I merge this?

No concerns on my end. Please merge

**Comment by melissabarber** [comment]
@force2b or @bdvorachek did this PR fix some translation issues introduced with Spring? If so, do we have a GitHub Issue for the translation bugs that we could link in this PR's description?

**Comment by force2b** [comment]
@melissabarber No gh issue since these are typically issues (i.e., missing or incorrect translations) identified by the LQA teams. They could be (and probably are) new content that wasn't translated in the original round by the translation team, meaning that the customer never would have seen the original issue fixed by this.

**Pull request merged**
