### PR TITLE
Additions to support Field Set driven columns in the Manage Allocations page

### PR DESCRIPTION
**Pull request by reiswarman**
# Critical Changes

# Changes

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by judisohn** [comment]
@coriobriensfdo Would you mind creating a Work Item for NPSP and mark it with the community contribution theme so this can be reviewed. [Please see the conversation here](https://powerofus.force.com/s/feed/0D51E00005P9kmeSAB) for context on where this came from. 

Thank you so much for the contribution @reiswarman - would you mind sending me an email at jsohn@salesforce.com so I can send you a Contributor License Agreement to sign? We'll need that done before the team can schedule a review. Thank you!

**Comment by coriobriensfdo** [comment]
Potentially fixes #1655

**Comment by coriobriensfdo** [comment]
Work Item [WI-8082061](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008IoKVIA0/view)

**Comment by judisohn** [comment]
CLA received and on file.

**Comment by andrewyu-salesforce** [comment]
Thank you for your contribution @reiswarman. The current PR will be closed since it has been included in PR #6152 that will go through standard code review and merge process into the master. Please let us know if there is any question.
CC @judisohn, @coriobriensfdo

**Pull request closed without merging**
