### PR TITLE
Gift Entry: Batch Defaults

### PR DESCRIPTION
**Pull request by voduyemi**
- Batch Defaults are now set on the Batch Gift Entry Form taking precedence over the Template level defaults that have been set. The values set on the Batch will always override the corresponding template field default value.

# Critical Changes

# Changes
## Gift Entry Enhancements
- We fixed an issue with field defaults. Before this release, the field defaults set in Template Builder didn't appear when you created a batch.

# Issues Closed

# Community Ideas Delivered

# New Metadata

# Deleted Metadata

### CODE REVIEW

**Comment by voduyemi** [comment]
**lurch: attach W-038958

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001HrEMQA0" target="_blank">W-038958</a>

**Comment by melissabarber** [comment]
@voduyemi and @ptewson-sfdo With this PR merging in after we release GE this week, I think we should have a GitHub Issue created and associated with this PR. Is it possible to get that done before you merge the PR?

**Comment by melissabarber** [comment]
@voduyemi I updated the description in this PR. Does it still look accurate and complete?

**Pull request merged**
